# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20180218_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('war', 'War'), ('anime', 'Anime')], max_length=120),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(default=2000, max_length=120),
        ),
    ]
